# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HPC WDR
email: cranfillkd@ornl.gov
description: >- # this means to ignore newlines until "baseurl:"
  The High Performance Computing Workforce Development and Retention Action Groupâ€™s 
  mission is to enable the Department of Energy National Laboratories and their 
  related computing communities to share their collective insight for inclusive 
  and equitable workforce development and retention for High Performance Computing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Socials
twitter_username: jekyllrb
github_username:  jekyll
facebook_username:  jekyll
twitter_username:  jekyll
youtube_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# CSS
sass:
  sass_dir: assets/css

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:path
  announcements:
    output: true
    permalink: /:collection/:path

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
favicon: "/assets/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  About: "about"
  Community: "community"
  HPC Jobs: "jobs"
  Blog: "blog"
  Cultivate Conversations: "conversations"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

primary-color: "#d5a300"
secondary-color: "#23468b"
success-color: "#28a745"
info-color: "#17a2b8"
warning-color: "#ffc107"
danger-color: "#dc3545"
light-color: "#F5F5F5"
dark-color: "#000a0d"

navbar-col: "#F5F5F5"
navbar-text-col: "#ffffff"
navbar-children-col: "#500e3d"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
